version: '3.1'

services:
  chat_app_sio:
    build:
      context: ./sio
      dockerfile: Dockerfile
    ports:
      - 5555:8080
    env_file:
      - ./.env
    volumes:
      - ./:/var/app/current
    networks:
      - chat-app-network
    depends_on:
      - chat_app_redis

  chat_app_redis:
    image: bitnami/redis:5.0.10
    user: root
    env_file:
      - ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - chat-app-network

  chat_app_redis_commander:
    container_name: ca-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=chat_app_redis
    ports:
        - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - chat-app-network
    depends_on:
      - chat_app_redis
  
  chat_app_web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    networks:
      - chat-app-network


volumes:
  redis_data:
    driver: local

networks:
  chat-app-network:
    driver: bridge
