export const TOGGLE_INPUT_MESSAGE_BOX = 'TOGGLE_INPUT_MESSAGE_BOX'
export const TOGGLE_MODAL_SETTINGS = 'TOGGLE_MODAL_SETTINGS'
export const TOGGLE_CLOCK_DISPLAY = 'TOGGLE_CLOCK_DISPLAY'
export const TOGGLE_KEYBOARD_SEND_SHORTCUT = 'TOGGLE_KEYBOARD_SEND_SHORTCUT'
export const RESET_MODAL_SETTINGS_CONFIG = 'RESET_MODAL_SETTINGS_CONFIG'

export const SET_UNSAFE_USERNAME = 'SET_UNSAFE_USERNAME'
export const SET_CHAT_ROOM = 'SET_CHAT_ROOM'
export const SIGN_OUT = 'SIGN_OUT'

export const SET_CONNECTED_USERS = 'SET_CONNECTED_USERS'

// TODO move those constants into another Reducers
export const ADD_MESSAGE = 'ADD_MESSAGE'